// yeah so this is a header LOL
#include <iostream>
#include <vector>



using namespace std;




#ifndef Monster_H
#define Monster_H
class Monster
{
    protected:
        string names [3] = {"goblin","Orc","Troll"};
        // img[0][0] = goblin
        vector<string> image;
        vector<vector<string>> img ={ {"Goblin",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMNx:coOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMW0;   .;o0WMMMMMMMMMMMMMMMMMMMMMMMNOo;;OMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMNd.    .;kNMMMMMMMMMMMMMMMMMMNkc'   cNMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMM0;      ,kNKkoc:;:cccoxONWO;    .oXMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMNx;.    .,.            ;c.    ;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMW0;                     .,oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMXo.                   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMX;       o      o     ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMNl                     '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMXc         __         .kMMMMMXOKWMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMXc                   lNMMMMWo .oXMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMNo.               .xNMMMMMWl   lNMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.          .'oKMMMMMMMMx.   lNMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:.        .oNMMMMMMMMMMk.   .OMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.           'OMMMMMMMMMMk..,cdXMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMXc              ,0MMMMMMMMMx..kWMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMNc                ;KMMMMMMM    cXMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMx.                 ,dkK    oxOOXMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMNc                         kNMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMX:                   '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMk.                    ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMM0'                      oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMX:                       lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMXc                        ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMWo                         .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMk.                          ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMM0doool. .:c::;;'''''''.     .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMK, oWMMMMMWNWWNNN0, 'xO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMO..kMMMMMMMMMMMMMk..xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMx..OMMMMMMMMMMMMMd '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMx.'0MMMMMMMMMMMMWl ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMO..dMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMN: cNMMMMMMMMMMMN: cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMX: 'xkONMMMMMMMMX; cXXkxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMM0;.''':0MMMMMMMMWl .''..xMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMNXXXXNMMMMMMMMMMNOkOOOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
      },{"Demon",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOkNMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN: ,OWMMMMMMNkl;,,,:oONMMMMMMMMMMWWWMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl  .xWMMMMK;         ,dXMMMMMMMNooNMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .oNMMX;            ,0MMMMWO; ;XMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .o0Oc              ;0WMXl.  ;XMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:   .     -   -       .,:.  .;kWMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkoc;'                    .c0WMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,              'cx0XWMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:   ___     ;kNMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:          .xMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc          .xMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,         ,KMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,      .c0MMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'      'OWMMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo.        .dKWMMMMMMMMMMMMMMMMMMMMMM",
      "MX0XMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNXKOkd:.            .;okO0KKKKKKKXWMMMMMMMMM",
      "MXc'oKWMMMMMMMMMMMMMMMMMMMMWd,',,,,''..                      ........'kMMMMMMMMM",
      "MMX; .dNMMMMMMMMMMMMMMMMMMWx.                .......                 .OMMMMMMMMM",
      "MMMk.  ,dKWMMMMMMMMMMMMMMMk.                 c0KKK0:                 ;XMMMMMMMMM",
      "MMMX:    .dNMMMMMMMMMMMMMX;                  .:OWK;                  :NMMMMMMMMM",
      "MMMMO'     cXMMMMMMMMMMMWd.                   .xW0,                  :NMMMMMMMMM",
      "MMMMWd.     ,0MMMMMMMMMMN:                    oWMNl                  :NMMMMMMMMM",
      "MMMMMXc      .kWMMMMMMMMK,        .dx.       ;KMMMk.     ,d:.        cNMMMMMMMMM",
      "MMMMMMXc      .dNMMMMMMMk.        cWO.      .kMMMMx.    .xM0,        ;XMMMMMMMMM",
      "MMMMMMMNl       :KMMMMMWl         dMx.      lWMMWK;     .xMK;        .OMMMMMMMMM",
      "MMMMMMMMNo.      ,0MMMMX;        .OMx.     .oNMWx.      .xMK,        .xMMMMMMMMM",
      "MMMMMMMMMWd.      'O0ONx.        ;XMd        ,ol.       .xMX;         dMMMMMMMMM",
      "MMMMMMMMMMWx.      .'dX:         lWWl                   .kMWl         dMMMMMMMMM",
      "MMMMMMMMMMMW0c.     .kNx'     ,ccOMK,                   .OMMd         dMMMMMMMMM",
      "MMMMMMMMMMMMMWO;.    ,KNc     dMMMMd.                   .OMMXd;.    ,oKMMMMMMMMM",
      "MMMMMMMMMMMMMMNd',,   ,c.     oMMMN:                    .OMMMNc     oMMMMMMMMMMM",
      "MMMMMMMMMMMMMMXxxXXc          dMMMk.                    .OMMWx.     oMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMNd'       ;KMMWx''........',;;,,,,,'';OMM0,      dMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMXxc;,,;c0MMMNo',,,,,,;,,,'.......',cKMWo      ;XMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMX;                     .OMW0l:;;:l0MMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,                     .OMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.                     .OMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:         .ldoo'       '0MMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.         cWMMMo       :NMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,         '0MMMMx.      dMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:         .xMMMMd       oMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.         ,KMMMMx.      dMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd          cNMMMMx.      dMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl          dMMMMMx.      dMMMMMMMMMMMMMMMMMMMMMMM",
      "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:         .OMMMMMx.     .xMMMMMMMMMMMMMMMMMMMMMMM"
    },{"Dragon with a party hat ",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0lxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,.oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  'cox0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;      .;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:         ,OMMMMMMMMMMMMMMMMMMMMWNXK0XWMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMWNKOkxxxxxO00O0XWMMMMMMMX;     .',,,:xXMMMMMMMMMMMMMXkdl:,'....,:d0NMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMN0dl:,..       .,:cld0WMMMMMMN:  .;::,.    'OWMMMMMMMMMMMKd:'          .'c0MMMMMMMMMM",
    "MMMMMMMMMMMWKd:'          .:dOKNWMMMMMMMMMMMWc.;:'.        '0MMMMMMMMMMMMMMNx.           'kWMMMMMMMM",
    "MMMMMMMMMXx:.           .lXWMMMMMMMMMMMMMMMMWk:'     //     oWMMMMMMMMMMMMMMN:            .dWMMMMMMM",
    "MMMMMMMXo'              ;XMMMMMMMMMMMMMMMMMMWl              .OMMMMMMMMMMMMMMO.             '0MMMMMMM",
    "MMMMMWO,                cNMMMMMMMMMMMMMMMMMM0'        .;:.   :NMMMMMMMMMMMMX:               ,kNMMMMM",
    "MMMMXo.                 .xWMMMMMMMMMMMMMMMMWo         ,KMXkocdNMMMMMMMMMMMWo                  cXMMMM",
    "MMWO;       ...          .dNMMMMMMMMMMMMMMMX;         lWMMMMMMMMMMMMMMMMWKc.             .;:,..:KMMM",
    "MNo.    .cxO0K0o.          ;kXWMMMMMMMMMMMMx.        .OMMMMMMMMMMMMMMMNk:.              ;0WMWXOkKMMM",
    "MXxododkXWMMMMWk.            .;lkKNWMMMMMNx.         :NMMMMMMMMMMMN0xc'                ,KMMMMMMMMMMM",
    "MMMMMMMMMMMMXxc;,'.              ..,coxxo;           ;KWMMMMWNKOdc'.                   cWMMMMMMMMMMM",
    "MMMMMMMMMMMMXkOXNWXk;                                 .;::::,..                  .''.. ;XMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMM0'                                                       .:dkKNNX0kONMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMNo':odooc.                                               .kWMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMKdOWMMMMN: .;l:.                                ',..     lWMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMNc'kWMWKo.                  .';;,'.    cNWXKOxo,.dMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMXdOMMMMMWo                .d0NWWWWKx;  lWMMMMMMN0KWMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMk.             .cKMMMMMMMMMNx,lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,           .'dWMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:           .cOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;           .lOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,          .oKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.         .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo         ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,        ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl        :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMN0XMMMMMMMMMMMWx.       cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMO';KMMMMMMMMMWk.       lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMd  ,OWMMMMMMNd.      .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMx.  .oKXX0xo;       .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMNo.   ....         .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMWk,.          .;lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMW0xl:;,,;cokXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
  }



    };

        string name;
        int hp;
        int maxhp;
        bool alive;
        int strength;
    public:
        Monster();
        Monster(int diff);
        Monster(string n,int h,int s);
        string getName();
        void setName(string s);
        int getHp();
        void setHp(int h);
        int getMaxHp();
        void setMaxHp(int m);
        int getStrength();
        void setStrength(int s);
        bool isAlive();
        void setAlive(bool b);
        int attack();
        void takeDmg(int dmg); // added these to the header for you so that the program will compile
        void monsterDieText();
        void printImage();
};
#endif
#ifndef Item_H
#define Item_H
class Item
{
    protected:
        string weps [5] = {"Red Shell", "Master Sword", "AK-47", "Ray Gun", "Nuclear Warhead"};
        string tools[5] = {"Swirling Red Potion","Healing Potion","Dr. Pepper","Pizza Slice", "Heroin"};
        //string
        int strengthmod;
        int uses;
        string name;
        int type;
    public:
        Item();
        Item(string n, int s);
        string getName();
        void setName(string n);
        int getStrength();
        void setStrength(int s);
        int getUses();
        void setUses(int u);
        void printitem();
        int getType();
};
#endif
// that's a big class lol
#ifndef Character_H
#define Character_H
class Character
{
    protected:
        string name;
        int hp;
        int maxhp;
        int strength;
        int mana;
        int maxmana;
        bool alive;
        vector<Item> inventory;
        int level;
        int xp;
        int gold;
    public:
        Character();
        Character(string n);
        string getName();
        void setName(string s);
        int getHp();
        void setHp(int h);
        int getMaxHp();
        void setMaxHp(int m);
        int getStrength();
        void setStrength(int s);
        int getMana();
        void setMana(int m);
        int getMaxMana();
        void setMaxMana(int m);
        bool isAlive();
        void setAlive(bool b);
        void takeDmg(int dmg);
        int attack();
        void characterDieText();
        int getXp();
        void setXp(int x);
        int getLevel();
        void setLevel(int l);
        void levelup();
        void setGold(int g);
        int getGold();
        vector<Item> getInventory();
        void setInventory(vector<Item> v);
};
#endif


#ifndef Map_H
#define Map_H
class Map{
    protected:
        vector<vector<int>> area;
        int playerx;
        int playery;
        int difficult;
    public:
        Map(int x);
        Map();
        void printMap();
        void fillMap();
        int move(int x, int y);
        vector<vector<int>> makeMap(int x,int y);
        vector<vector<int>> generateRooms(vector<vector<int>> vec);
        vector<vector<int>> generateHalls(vector<vector<int>> vec,int x, int y);
        vector<vector<int>> getMap();
        void repopulate(int n);
};

#endif
#ifndef Battle_H
#define Battle_H
class Battle{
    protected:
        Character* cha;
        Character c; // this is useless, and very frustrating
        Monster m;
    public:
        Battle(Character* ca, Monster mo);
        int fight();
        int getAttackInput();
        void displayStats();
        void healthbar(int max, int current);
};
#endif
